application:
  twelvedata.apikey: '6e00d314e77840d4ac18eef23682f49f'
  limit.startValue: 1000
  db.currency: USD

springdoc:
  swagger-ui:
    path: '/documentation'

spring:
  application.name: 'bank-account'

#  docker.compose.profiles.active: [default, test]

  liquibase:
    enabled: 'true'
    change-log: 'classpath:/db/changelog/changelog-master.xml'
    contexts: dev

  cassandra:
    local-datacenter: 'dc1'
    keyspace-name: 'currencyCache'
    schema-action: CREATE_IF_NOT_EXISTS
    keyspace.create: "CREATE KEYSPACE currencyCache WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};"
    contact-points: 'cassandra'

  data:
    cassandra:
      local-datacenter: 'dc1'
      keyspace-name: 'currencyCache'
      port: '9042'
      schema-action: CREATE_IF_NOT_EXISTS
      create-keyspace: true

  jpa:
    show-sql: true
    properties.hibernate.dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate.ddl-auto: none

  datasource:
    url: 'jdbc:postgresql://postgres:5432/bankdb'
    username: 'postgres'
    password: 'qwerty'
    driver-class-name: 'org.postgresql.Driver'

  h2.console:
    enabled: false
    path: '/h2-console'


logging:
  level:
    org.springframework.web: DEBUG
    ru.egorov: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG