spring:
  application.name: 'bank-account'
  liquibase.enabled: 'false'

  cassandra:
    local-datacenter: 'datacenter1'
    keyspace-name: 'currencyCache'
    schema-action: 'RECREATE'

  data:
    cassandra:
      local-datacenter: 'datacenter1'
      keyspace-name: 'currencyCache'
      port: '9142'
      contactpoints: 'localhost'
      schema-action: 'RECREATE'

twelvedata.apikey: '6e00d314e77840d4ac18eef23682f49f'

logging:
  level:
    org.springframework.web: ERROR
    ru.egorov: DEBUG