application:
  twelvedata.apikey: '6e00d314e77840d4ac18eef23682f49f'

spring:
  application.name: 'bank-account'

  docker.compose.profiles.active: [default, test]

  liquibase:
    enabled: 'true'
    change-log: 'classpath:/db/changelog/changelog-master.xml'
    contexts: test

  cassandra:
#    local-datacenter: 'datacenter1'
    keyspace-name: 'currencyCache'
    schema-action: 'RECREATE'

  data:
    cassandra:
      local-datacenter: 'datacenter1'
      keyspace-name: 'currencyCache'
      port: '9142'
      contactpoints: 'localhost'
      schema-action: 'RECREATE'


  jpa:
    show-sql: true
    properties.hibernate.dialect: 'org.hibernate.dialect.H2Dialect'
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: 'jdbc:h2:mem:testdb'
    username: 'postgres'
    password: 'qwerty'
    driver-class-name: 'org.h2.Driver'


logging:
  level:
    org.springframework.web: ERROR
    ru.egorov: DEBUG